// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MqttMessageBody.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#import <objc/Message.h>

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MqttMessageBody_Attachment;
@class MqttMessageBody_UserInfoBody;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum MqttMessageBody_ChatType

typedef GPB_ENUM(MqttMessageBody_ChatType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  MqttMessageBody_ChatType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  MqttMessageBody_ChatType_Singl = 0,
  MqttMessageBody_ChatType_Many = 1,
};

GPBEnumDescriptor *MqttMessageBody_ChatType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MqttMessageBody_ChatType_IsValidValue(int32_t value);

#pragma mark - MqttMessageBodyRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MqttMessageBodyRoot : GPBRootObject
@end

#pragma mark - MqttMessageBody

typedef GPB_ENUM(MqttMessageBody_FieldNumber) {
  MqttMessageBody_FieldNumber_Num = 1,
  MqttMessageBody_FieldNumber_Content = 2,
  MqttMessageBody_FieldNumber_Fromid = 3,
  MqttMessageBody_FieldNumber_Toid = 4,
  MqttMessageBody_FieldNumber_From = 5,
  MqttMessageBody_FieldNumber_To = 6,
  MqttMessageBody_FieldNumber_Att = 7,
  MqttMessageBody_FieldNumber_Chattype = 8,
};

/**
 * 消息体
 **/
@interface MqttMessageBody : GPBMessage

@property(nonatomic, readwrite) int32_t num;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *toid;

/** 发信者 */
@property(nonatomic, readwrite, strong, null_resettable) MqttMessageBody_UserInfoBody *from;
/** Test to see if @c from has been set. */
@property(nonatomic, readwrite) BOOL hasFrom;

/** 收信者 */
@property(nonatomic, readwrite, strong, null_resettable) MqttMessageBody_UserInfoBody *to;
/** Test to see if @c to has been set. */
@property(nonatomic, readwrite) BOOL hasTo;

/** 附件 */
@property(nonatomic, readwrite, strong, null_resettable) MqttMessageBody_Attachment *att;
/** Test to see if @c att has been set. */
@property(nonatomic, readwrite) BOOL hasAtt;

@property(nonatomic, readwrite) MqttMessageBody_ChatType chattype;

@end

/**
 * Fetches the raw value of a @c MqttMessageBody's @c chattype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t MqttMessageBody_Chattype_RawValue(MqttMessageBody *message);
/**
 * Sets the raw value of an @c MqttMessageBody's @c chattype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetMqttMessageBody_Chattype_RawValue(MqttMessageBody *message, int32_t value);

#pragma mark - MqttMessageBody_UserInfoBody

typedef GPB_ENUM(MqttMessageBody_UserInfoBody_FieldNumber) {
  MqttMessageBody_UserInfoBody_FieldNumber_Num = 1,
  MqttMessageBody_UserInfoBody_FieldNumber_Username = 2,
  MqttMessageBody_UserInfoBody_FieldNumber_Userid = 3,
  MqttMessageBody_UserInfoBody_FieldNumber_Avatar = 4,
  MqttMessageBody_UserInfoBody_FieldNumber_Mobile = 5,
};

@interface MqttMessageBody_UserInfoBody : GPBMessage

@property(nonatomic, readwrite) int32_t num;

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mobile;

@end

#pragma mark - MqttMessageBody_Attachment

typedef GPB_ENUM(MqttMessageBody_Attachment_FieldNumber) {
  MqttMessageBody_Attachment_FieldNumber_Content = 1,
  MqttMessageBody_Attachment_FieldNumber_IsPush = 2,
};

@interface MqttMessageBody_Attachment : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite) BOOL isPush;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
